title: "Oma GitHub Pages -sivuni"
description: "Tämä on minun projektini GitHub Pagesissa!"
author: null  # Tämä estää tekijän nimen näyttämisen
theme: jekyll-theme-minimal  # Tämän voit vaihtaa toiseen teemaan, jos haluat
