title: "Tervetuloa!"
description: "Tämä on oma GitHub Pages -sivuni, joka on osa Pilvipalvelut -kurssia."
author: Janina Niemelä
# Muuta tämä polku omaan kuvaasi
theme: jekyll-theme-minimal  # Tämän voit vaihtaa toiseen teemaan, jos haluat


 
